# Generated by Django 2.2.13 on 2020-06-30 09:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=10)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, size=None)),
                ('snippet_one', models.ImageField(default='snippet1.png', null=True, upload_to='snippets/%Y/%m/%D/')),
                ('snippet_two', models.ImageField(default='snippet2.png', null=True, upload_to='snippets/%Y/%m/%D/')),
                ('snippet_three', models.ImageField(default='snippet3.png', null=True, upload_to='snippets/%Y/%m/%D/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='clips/%Y/%m/%D/')),
                ('link', models.URLField(blank=True, default='url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
