language: python
python:
  - "3.7"

services:
  - postgresql

env:
  global: 
  - CC_TEST_REPORTER_ID=ca396cf7f8790934b4bdd40c07a18fda6007ce6916cd67b228ee035d5ac2ccc7

install:
  - pip install -q pipenv
  - pip install coveralls 
  - pipenv install 

before_script:
  - psql -c 'create database rachis;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source='.' manage.py test
  - coverage report

after_success:
  - coveralls